//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NitcotekAssignmentEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountsChart
    {
        public System.Guid ID { get; set; }
        public string NameAR { get; set; }
        public string NameEN { get; set; }
        public string Number { get; set; }
        public short FK_Transaction_Type_ID { get; set; }
        public bool Allow_Entry { get; set; }
        public bool Is_Active { get; set; }
        public long User_ID { get; set; }
        public System.DateTime Creation_Date { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.Guid> Parent_ID { get; set; }
        public string Parent_Number { get; set; }
        public short Chart_Level_Depth { get; set; }
        public Nullable<short> FK_Cost_Center_Type_ID { get; set; }
        public long Branch_ID { get; set; }
        public long Org_ID { get; set; }
        public Nullable<System.Guid> FK_Work_Fields_ID { get; set; }
        public Nullable<short> noOfChilds { get; set; }
    }
}
