//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NitcotekAssignmentEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JournalHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JournalHeader()
        {
            this.JournalDetails = new HashSet<JournalDetail>();
        }
    
        public int JournalHeadrerID { get; set; }
        public Nullable<System.DateTime> DateOfEntry { get; set; }
        public string ReferenceNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JournalDetail> JournalDetails { get; set; }
    }
}
